# Generated by Django 6.0 on 2025-12-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0060_reportechamizal_estatus_reportecultura_estatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefuentes',
            name='operativo_especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportefuentes',
            name='trabajo_ciudadania',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportefuentes',
            name='trabajo_diario',
            field=models.BooleanField(default=False),
        ),
    ]
