# Generated by Django 6.0 on 2025-12-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0061_reportefuentes_operativo_especial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefuentes',
            name='operativo_comentarios',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
