# Generated by Django 6.0 on 2026-02-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0062_reportefuentes_operativo_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefuentes',
            name='folio_pac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
