# Generated by Django 6.0 on 2026-02-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0063_alter_reportefuentes_folio_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefuentes',
            name='folio_pac',
            field=models.IntegerField(null=True),
        ),
    ]
